/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JRasterizer;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Lesson0 classUnderTest = new Lesson0(4);
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
